### ISSUE TITLE
bug: the button in home page isn't responsive, please fix it

### ISSUE THREAD

**Issue by RichardPompeo** [RichardPompeo/personspace#4]
<img width="127" alt="image" src="https://github.com/RichardPompeo/personspace/assets/65838395/4f35e0a4-d109-4f2a-a32a-1ae5dfdea018">

Branch: [home-page](https://github.com/RichardPompeo/personspace/pull/2)

**Comment by MFelipeSilva** [comment]
fix: adjusted home button
